# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-26 02:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('LoginIP', models.CharField(max_length=30)),
                ('LoginStatus', models.BooleanField()),
                ('LoginFail', models.IntegerField()),
                ('LoginTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivilegesInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupID', models.CharField(max_length=20)),
                ('Group', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('LoginId', models.CharField(max_length=30)),
                ('Pwd', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=20)),
                ('Sex', models.BooleanField(default=True)),
                ('Phone', models.IntegerField()),
                ('Address', models.CharField(max_length=100)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('LastLogin', models.DateTimeField(auto_now=True)),
                ('GroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.PrivilegesInfo')),
            ],
        ),
        migrations.AddField(
            model_name='loginlog',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.UserInfo'),
        ),
    ]
