# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-07 04:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('LoginIP', models.GenericIPAddressField(null=True)),
                ('LoginStatus', models.CharField(choices=[('T', 'Success'), ('F', 'Fail')], max_length=10, null=True)),
                ('LoginFail', models.IntegerField(null=True)),
                ('LoginTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrivilegesInfo',
            fields=[
                ('GroupID', models.AutoField(primary_key=True, serialize=False)),
                ('Group', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('UserID', models.AutoField(primary_key=True, serialize=False)),
                ('LoginId', models.CharField(max_length=30, unique=True)),
                ('Pwd', models.CharField(max_length=30)),
                ('Name', models.CharField(max_length=20)),
                ('Sex', models.CharField(choices=[('M', '男'), ('F', '女')], max_length=4, null=True)),
                ('Mail', models.EmailField(max_length=254, null=True)),
                ('Phone', models.IntegerField(null=True)),
                ('Address', models.CharField(max_length=100, null=True)),
                ('CreateDate', models.DateTimeField(auto_now_add=True)),
                ('LastLogin', models.DateTimeField(auto_now=True)),
                ('GroupID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.PrivilegesInfo')),
            ],
        ),
        migrations.AddField(
            model_name='loginlog',
            name='UserID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.UserInfo'),
        ),
    ]
