# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-26 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20171226_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privilegesinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Sex',
            field=models.CharField(choices=[('M', '男'), ('F', '女')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='LoginFail',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='LoginIP',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='LoginStatus',
            field=models.CharField(choices=[('T', 'Success'), ('F', 'Fail')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='privilegesinfo',
            name='GroupID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Name',
            field=models.CharField(max_length=20),
        ),
    ]
