# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-26 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_auto_20171226_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='LoginId',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
