# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-28 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20171226_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='LoginFail',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='LoginIP',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='LoginStatus',
            field=models.CharField(blank=True, choices=[('T', 'Success'), ('F', 'Fail')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Mail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='Sex',
            field=models.CharField(blank=True, choices=[('M', '男'), ('F', '女')], max_length=4, null=True),
        ),
    ]
